# Add seed data here. Seed your database with `rake db:seed`

LibraryParser.parse

# DATA ADDED BY HAND:
# a1 = Artist.create(name: "A$AP Rocky")
# a2 = Artist.create(name: "Adele")
# a3 = Artist.create(name: "Beyonce")
# a4 = Artist.create(name: "DJ Khaled")
# a5 = Artist.create(name: "Jamie xx")
# a6 = Artist.create(name: "Jay-Z & Kanye West")
# a7 = Artist.create(name: "Kelly Rowland")
# a8 = Artist.create(name: "Kendrick Lamar")
# a9 = Artist.create(name: "Rhianna")
# a10 = Artist.create(name: "The Weekend")
# a11 = Artist.create(name: "Tyler the Creator")
#
# s1 = Song.create(name: "Peso", artist_id: 1)
# s2 = Song.create(name: "Rolling in the Deep", artist_id: 2)
# s3 = Song.create(name: "Someone Like You", artist_id: 2)
# s4 = Song.create(name: "1+1", artist_id: 3)
# s5 = Song.create(name: "Countdown", artist_id: 3)
# s6 = Song.create(name: "I'm On One (ft. Drake, Rick Ross, & Lil Wayne)", artist_id: 4)
# s7 = Song.create(name: "Far Nearer", artist_id: 5)
# s8 = Song.create(name: "N****s In Paris", artist_id: 6)
# s9 = Song.create(name: "Otis (ft. Otis Redding)", artist_id: 6)
# s10 = Song.create(name: "Motivation (ft. Lil Wayne)", artist_id: 7)
# s11 = Song.create(name: "A.D.H.D", artist_id: 8)
# s12 = Song.create(name: "We Found Love (ft. Calvin Harris)", artist_id: 9)
# s13 = Song.create(name: "House of Balloons", artist_id: 10)
# s14 = Song.create(name: "This Morning", artist_id: 10)
# s15 = Song.create(name: "Yonkers", artist_id: 11)
#
# g1 = Genre.create(name: "country")
# g2 = Genre.create(name: "dance")
# g3 = Genre.create(name: "folk")
# g4 = Genre.create(name: "hip-hop")
# g5 = Genre.create(name: "house")
# g6 = Genre.create(name: "indie")
# g7 = Genre.create(name: "pop")
# g8 = Genre.create(name: "rap")
# g9 = Genre.create(name: "rock")
#
# SongGenre.create(song_id: 1, genre_id: 2)
# SongGenre.create(song_id: 2, genre_id: 3)
# SongGenre.create(song_id: 3, genre_id: 1)
# SongGenre.create(song_id: 4, genre_id: 5)
# SongGenre.create(song_id: 5, genre_id: 7)
# SongGenre.create(song_id: 6, genre_id: 7)
# SongGenre.create(song_id: 7, genre_id: 9)
# SongGenre.create(song_id: 8, genre_id: 2)
# SongGenre.create(song_id: 9, genre_id: 3)
# SongGenre.create(song_id: 10, genre_id: 5)
# SongGenre.create(song_id: 11, genre_id: 8)
# SongGenre.create(song_id: 12, genre_id: 6)
# SongGenre.create(song_id: 13, genre_id: 4)
# SongGenre.create(song_id: 14, genre_id: 2)
# SongGenre.create(song_id: 15, genre_id: 3)
